In [35]:
import pandas as pd
df_train = pd.read_csv('nlp_train.csv')

In [36]:
df.head()

text  target  \
0  I was wondering if anyone out there could enli...       7   
1  A fair number of brave souls who upgraded thei...       4   
2  well folks, my mac plus finally gave up the gh...       4   
3  \nDo you have Weitek's address/phone number?  ...       1   
4  From article <C5owCB.n3p@world.std.com>, by to...      14   

                category  
0              rec.autos  
1  comp.sys.mac.hardware  
2  comp.sys.mac.hardware  
3          comp.graphics  
4              sci.space

In [37]:
print(df.iloc[1,0])

A fair number of brave souls who upgraded their SI clock oscillator have
shared their experiences for this poll. Please send a brief message detailing
your experiences with the procedure. Top speed attained, CPU rated speed,
add on cards and adapters, heat sinks, hour of usage per day, floppy disk
functionality with 800 and 1.4 m floppies are especially requested.

I will be summarizing in the next two days, so please add to the network
knowledge base if you have done the clock upgrade and haven't answered this
poll. Thanks.


In [38]:
print(df.iloc[1,1])

4


In [39]:
print(df.iloc[3,0])


Do you have Weitek's address/phone number?  I'd like to get some information
about this chip.



In [40]:
from sklearn.feature_extraction.text import CountVectorizer
d1 = "I love programming"
d2 = "programming is interesting"
d3  = "I love pizza very very much"
document = [d1, d2, d3]
vectorizer = CountVectorizer()
x = vectorizer.fit_transform(document)
print(vectorizer.vocabulary_)
print(x.toarray())



{'love': 2, 'programming': 5, 'is': 1, 'interesting': 0, 'pizza': 4, 'very': 6, 'much': 3}
[[0 0 1 0 0 1 0]
 [1 1 0 0 0 1 0]
 [0 0 1 1 1 0 2]]


In [41]:
import numpy as np

doc = df.iloc[:,0]
#arr = np.array(doc)
document = doc.astype(str).tolist() 
vectorizer = CountVectorizer(max_features = 300)
x = vectorizer.fit_transform(document)
print(vectorizer.vocabulary_)
print(x.toarray())
print(x.shape)

{'was': 275, 'if': 127, 'anyone': 30, 'out': 188, 'there': 248, 'could': 64, 'me': 158, 'on': 181, 'this': 254, 'car': 57, 'the': 244, 'other': 186, 'day': 67, 'it': 132, 'to': 260, 'be': 41, 'from': 98, 'called': 55, 'were': 279, 'really': 211, 'in': 128, 'of': 178, 'is': 131, 'all': 23, 'know': 137, 'can': 56, 'name': 167, 'years': 296, 'where': 282, 'made': 152, 'or': 184, 'you': 298, 'have': 116, 'please': 195, 'mail': 153, 'number': 177, 'who': 285, 'their': 245, 'for': 96, 'send': 220, 'your': 299, 'with': 290, 'and': 27, 'are': 32, 'will': 287, 'next': 171, 'two': 264, 'so': 226, 'done': 75, 'thanks': 242, 'well': 278, 'my': 166, 'up': 266, 'after': 20, 'life': 143, 'as': 34, 'way': 276, 'back': 39, 'new': 170, 'bit': 50, 'than': 241, 'into': 130, 'that': 243, 'does': 72, 'any': 29, 'when': 281, 'make': 154, 'an': 26, 'but': 52, 'since': 225, 'don': 74, 'had': 113, 'more': 161, 'has': 115, 'about': 17, 'line': 145, 'like': 144, 'just': 135, 'through': 258, 'what': 280, 'probably

In [42]:
from sklearn.datasets import fetch_20newsgroups
newsgroups_train = fetch_20newsgroups(subset='train')
newsgroups_train.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [43]:
#newsgroups_train.data

In [44]:
newsgroups_test = fetch_20newsgroups(subset='test')
newsgroups_test.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [45]:
cat = ["alt.atheism" , "comp.graphics" , "sci.space"]

train_cat_data = fetch_20newsgroups(subset = "train" , categories = cat)
test_cat_data = fetch_20newsgroups(subset = "test" ,categories = cat)

In [46]:
train_cat_data.target_names

['alt.atheism', 'comp.graphics', 'sci.space']

In [47]:
train_cat_data.target.shape

(1657,)

In [48]:
cat = ["alt.atheism" , "comp.graphics" , "sci.space"]



In [49]:
df.shape

(11314, 3)

In [50]:
df_test = pd.read_csv('newsgroups_test.csv')

In [51]:
df_train["category"].unique()

array(['rec.autos', 'comp.sys.mac.hardware', 'comp.graphics', 'sci.space',
       'talk.politics.guns', 'sci.med', 'comp.sys.ibm.pc.hardware',
       'comp.os.ms-windows.misc', 'rec.motorcycles', 'talk.religion.misc',
       'misc.forsale', 'alt.atheism', 'sci.electronics', 'comp.windows.x',
       'rec.sport.hockey', 'rec.sport.baseball', 'soc.religion.christian',
       'talk.politics.mideast', 'talk.politics.misc', 'sci.crypt'],
      dtype=object)

In [52]:
df_test["category"].unique()

array(['sci.space', 'comp.graphics', 'alt.atheism'], dtype=object)

In [53]:
cat = ['sci.space', 'comp.graphics', 'alt.atheism']

df_sel_col_train = df[df["category"].isin(cat)]

In [54]:
df_sel_col_train

text  target  \
3      \nDo you have Weitek's address/phone number?  ...       1   
4      From article <C5owCB.n3p@world.std.com>, by to...      14   
13     \n   {Description of "External Tank" option fo...      14   
15     \nDon't be so sure.  Look what happened to Jap...       0   
16     \nI certainly do use it whenever I have to do ...       1   
...                                                  ...     ...   
11275  \nThis sounds like another of Ali AbuTaha's 57...      14   
11276  A new alternative to Scouting for those "unacc...       0   
11286  \n\n\n\n\nThe HGA isn't all that reflective in...      14   
11289  I have a Diamond Speedstar 24X board that I wa...       1   
11312  \nWouldn't this require a hyper-sphere.  In 3-...       1   

            category  
3      comp.graphics  
4          sci.space  
13         sci.space  
15       alt.atheism  
16     comp.graphics  
...              ...  
11275      sci.space  
11276    alt.atheism  
11286      sci.space  
11289  comp.graphics  
11312  comp.graphics  

[1657 rows x 3 columns]

In [55]:
df_sel_col_train.iloc[5:6]

text  target     category
20  \n[...]\n\nThese don't seem like "little thing...       0  alt.atheism

In [56]:
df_sel_col_train.shape

(1657, 3)

In [57]:
df_sel_col_train['text']

3        \nDo you have Weitek's address/phone number?  ...
4        From article <C5owCB.n3p@world.std.com>, by to...
13       \n   {Description of "External Tank" option fo...
15       \nDon't be so sure.  Look what happened to Jap...
16       \nI certainly do use it whenever I have to do ...
                               ...                        
11275    \nThis sounds like another of Ali AbuTaha's 57...
11276    A new alternative to Scouting for those "unacc...
11286    \n\n\n\n\nThe HGA isn't all that reflective in...
11289    I have a Diamond Speedstar 24X board that I wa...
11312    \nWouldn't this require a hyper-sphere.  In 3-...
Name: text, Length: 1657, dtype: object

In [63]:
df_sel_col_train.dropna(inplace=True)
df_test.isnull().sum()

/tmp/ipykernel_3110/2135118914.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sel_col_train.dropna(inplace=True)


text        0
target      0
category    0
dtype: int64

In [61]:
df_sel_col_train.isnull().sum()

text        0
target      0
category    0
dtype: int64

In [64]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x_train=cv.fit_transform(df_sel_col_train["text"])
y_train=df_sel_col_train['category']

x_test = cv.transform(df_test["text"])
y_test=df_test['category']


In [65]:
x_train.shape

(1624, 23598)

In [76]:
y_train.shape

(1624,)

In [66]:
from sklearn.naive_bayes import BernoulliNB
model = BernoulliNB()
model.fit(x_train,y_train)

BernoulliNB()

In [72]:
pridict = model.predict(x_test)
pridict[:5]

array(['sci.space', 'comp.graphics', 'comp.graphics', 'comp.graphics',
       'comp.graphics'], dtype='<U13')

In [75]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(pridict,y_test)
ac

0.8611615245009074

In [80]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
x_trainf = tf.fit_transform(df_sel_col_train["text"])
y_trainf = df_sel_col_train["category"]

x_testf = cv.transform(df_test["text"])
y_testf = df_test['category']

In [82]:
from sklearn.naive_bayes import MultinomialNB
mm = MultinomialNB()
mm.fit(x_trainf,y_trainf)

MultinomialNB()

In [83]:
m=mm.predict(x_testf)
m

array(['sci.space', 'comp.graphics', 'comp.graphics', ..., 'alt.atheism',
       'comp.graphics', 'sci.space'], dtype='<U13')

In [85]:
accuracy_score(m,y_test)

0.8992740471869328